### ISSUE TITLE
Offer a way to update the general configuration from the CTL

### ISSUE THREAD

**Issue by psanders** [fonoster/routr-ctl#5]
Routr Server and the Web UI will allow updating the general configs for the datasources that accept writing operations. This should be implemented in the CTL too.

**Comment by psanders** [comment]
Getting this when trying to update the general config:

java.lang.NullPointerException
	at io.routr.ctl.CmdApply.apply(CmdApply.java:74)
	at io.routr.ctl.CmdApply.run(CmdApply.java:69)
	at io.routr.ctl.Main.main(Main.java:78)

**Comment by psanders** [comment]
Moved to https://github.com/orgs/fonoster/projects
